### ISSUE TITLE
Problem with file deletion

### ISSUE THREAD

**Issue by mchasal** [ear9mrn/MythRokuPlayer#5]
It appears that there is a major problem with the current file deletion fix. The last fix to prevent the deletion of 2 files that were recorded at the same time introduced this problem. 
The following line (#17) in mythtv_tv_del.php: 

$files = glob('../data/recordings/_' . RemoveExtension($db_field['basename'])  . '_');

tries to fetch basename from a DB query, but there was no DB query done in this file, so $db_field is not initialized. This causes it to delete ALL files in the recordings directory. RemoveExtension ends up returning NULL, so the pattern ends up being "../data/recordings/*". The basename should be pulled from the arguments passed into the script. You can look at the latest commit in the "bif" branch on my fork of your tree, hesitant to attach a pull request since some other things are different.

**Comment by rshendershot** [comment]
I use storage directories so my recordings can be found in  $DATA, $DATA/evaluation, $DATA/kids, etc.  This seems incompatible with the current deletion codebase.  I had to disable the check for recordings' file extension in $mythtvdata since it would always return an empty list.  With that, the TV list works (except for sort by category).  I haven't tried deletion and there's something also broken for me in the Movies menu.  I'm far enough along to want to continue so I wondered just what the status was?

also, I use this handbrake command and I don't get any syncing problems at all and the conversion is faster.  perhaps you'd find it also useful....

   /usr/bin/HandBrakeCLI --preset='iPhone & iPod Touch' -i $MYTHDIR/$MPGFILE -o $newname >> $LOGFILE 2>&1
