### ISSUE TITLE
Roku channel app stuck on "Retrieving..."

### ISSUE THREAD

**Issue by mspiceland** [ear9mrn/MythRokuPlayer#7]
I've followed the README instructions.  I can visit the test page http://192.168.1.102/mythweb/mythroku/mythtv_tv_test.php and appears to work fine, displaying all of my recorded shows.  When i load mythtv_tv_xml.php it displays "0 0" in the browser but viewing the source shows XML indicating 0 results.

I've loaded the Roku channel app using the private channel link over the web (listed on the Roku forum sticky first post).  I've configured it to use the same IP address and path, yet it gets stuck saying "Retrieving..."

What can I do to troubleshoot further?

Am I ok to use the private channel link to install instead of the one included in a git checkout?   I tried doing a make install using the git checkout but got the following:

$ make install
**\* Creating MythRokuPlayer.zip ***

> > removing old application zip zips/MythRokuPlayer.zip
> > creating destination directory zips
> > setting directory permissions for zips
> > creating application zip zips/MythRokuPlayer.zip
> > Source for MythRokuPlayer not found at ../MythRokuPlayer
> > **\* developer zip  MythRokuPlayer complete ***
> > Installing MythRokuPlayer to host 192.168.1.100
> > curl: (26) failed creating formpost data

Thanks for all the hard work putting this together, btw.  I'm hoping this will be fantastic once I get it working.

**Comment by ear9mrn** [comment]
Take a look at this on the Roku forum. 

http://forums.roku.com/viewtopic.php?f=28&t=33704&p=302366&hilit=mythtv#p301755

Check your apache logs and see if the GD library is installed. The "retrieving" error is usually because GD is not installed so the art work cannot be rendered write back here if that solves your problem (or not).

The version on the private channel and on git hub are the same so it should work with either but so you can scratch that itch of installing it yourself ensure that the directory your are running "make install" from is called MythRokuPlayer. I was able to replicate your error by changing my directory name to  MythRokuPlayer1.

:~/MythRokuPlayer1$ make install
**\* Creating MythRokuPlayer.zip ***

> > removing old application zip zips/MythRokuPlayer.zip
> > creating destination directory zips
> > setting directory permissions for zips
> > creating application zip zips/MythRokuPlayer.zip
> > Source for MythRokuPlayer not found at ../MythRokuPlayer
> > **\* developer zip  MythRokuPlayer complete ***

Let me know if this fixes the problem or not. Also, would you mind posting these issues to the same forum thread listed above (and I will respond with the same answers) as that is area IS more for true bugs and feature requests and I would like to keep general install issues and configuration stuff to the forum. 

Thanks for giving MythRokuPlayer a go, hope you get it working soon. Sorry that your are having issues, this is a very early version and we are trying to make the install process simpler and easier, what this space.

Let me know how you get on and if your problems are solved we can close the issue.

Pete.

**Comment by mspiceland** [comment]
Pete,

I think the root cause is that I have no .mp4 files yet.  I think that mythtv_tv_test.php lists all of the shows, regardless of format while mythtv_tv_xml.php only lists the .mp4 files.  Because I already had recordings, but none had the User Job #1 run, handbrake had not created any .mp4 files yet.  I verified this by manually running rokuencode.sh on one of the .mpg files to create a .mp4 file.  I then could go to mythtv channel and the one show that I manually ran showed up.  I am now waiting for some new recordings to see if it works on a full show after a recording.  I'm crossing my fingers that is all that it is.  I'll close this out tonight after I verify.

Thanks for the quick response!

**Comment by mspiceland** [comment]
Yeah, that was it!  In a quick test, it is working remarkably well.  The quality is great.  Thanks again for your hard work.

I suggest adding a message when the mythtv_*_xml.php returns zero results.  That way, it could display "no recordings" instead of what appeared to be stuck on "Retreiving...".

Thanks again!
